#
#server:
#  port: 9001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#spring:
#  application:
#     name: product
#  profiles:
#    active: dev
#  config:
#    uri: https://github.com/Truongcr/Configuration.git
#  datasource:
#     url: jdbc:mysql://localhost:3306/tramhuong
#     username: root
#     password: 123456
#  jpa:
#     hibernate:
#        ddl-auto: update
#     properties:
#        hibernate:
#           dialect: org.hibernate.dialect.MySQL55Dialect
#
spring:
  application:
     name: app
#  profiles:
#     active: dev
#  cloud:
#     config:
#        uri: http://localhost:8888
  datasource:
       url: jdbc:mysql://localhost:3306/tramhuong
       username: root
       password: 123456
  jpa:
       hibernate:
          ddl-auto: update
       properties:
          hibernate:
             dialect: org.hibernate.dialect.MySQL55Dialect
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIATNXTD35D4WU2TPZD
  secretKey: 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
  bucketName: app-tram-huong
server:
  port: 8086
#  Nv;M?)QkzX!pIUWbxzHIgpH7$uDhp8v%
